### ISSUE TITLE
CGH Tester Can't read xml config file

### ISSUE THREAD

**Issue by minghuaw** [Openhologram/Openholo#33]
The tester throws the following error message whenever trying to read a config file following the YouTube tutorial found on OpenHolo website. 

```cmd
Reading....D:\Downloads\Openholo_CGH_Tester\OpenHolo Input Data\config\Dice_TriMesh_1Channel.xml...file's extension is not 'xml'
Reading....D:\Downloads\Openholo_CGH_Tester\OpenHolo Input Data\config\Dice_LightField_1Channel.xml...file's extension is not 'xml'
Reading....D:\Downloads\Openholo_CGH_Tester\OpenHolo Input Data\config\Dice_DepthMap_1Channel.xml...file's extension is not 'xml'
Reading....D:\Downloads\Openholo_CGH_Tester\OpenHolo Input Data\config\Dice_PointCloud_1Channel.xml...file's extension is not 'xml'
Reading....D:\Downloads\Openholo_CGH_Tester\OpenHolo Input Data\config\Dice_WRP_1Channel.xml...file's extension is not 'xml'
```

Plus, as shown below the Generate Hologram button is grayed out even after manually typing in the Config Parameters. The PLY file loaded was the Dice example that comes with the CGH_Tester zip file. 

![Screenshot 2020-10-26 155132](https://user-images.githubusercontent.com/29760666/97236821-2e5eb980-17a3-11eb-9e98-9f5d4d39096a.png)

**Comment by mwnam** [comment]
please use github.

2020년 10월 27일 (화) 07:54, minghuaw <notifications@github.com>님이 작성:

**Comment by mwnam** [comment]
https://github.com/Openhologram/OpenholoRefAppGUI



2020년 10월 27일 (화) 09:50, Minwoo Nam <mwnam4642@gmail.com>님이 작성:

**Comment by minghuaw** [comment]
Thanks for the support. I think the problem actually lies in the .xml files that come with the CGH_Tester package. I was able to read config files using the xml files from the RefAppGUI repo.

I will close this issue now.
