### ISSUE TITLE
demo.cpp and Makefile required

### ISSUE THREAD

**Issue by suz53** [Openhologram/Openholo#36]
Hi, 

I was trying to write the first test.cpp based on the online doc: [http://openholo.org/doxygen/html/index.html#Examples](url)

The build command is: `g++ test.cpp -I/path/to/Reference/include -L/path/to/Reference/lib`. 
The test.cpp is exactly same with the online doc example (with a `main()` func added). 
I am running on a Nvidia AGX Jetson platform (Debian, Cuda installed).

However, I am facing the compilation error:
`error: 'ophPointCloud' was not declared in this scope` and so on.

Could you please provide a `tests/demo.cpp` and `tests/Makefile` to better guide how to use? Thanks.

**Comment by Openhologram** [comment]
https://github.com/Openhologram/OpenholoRefApp/tree/master/cpp
